# Streamlit生產環境配置

[global]
developmentMode = false
logLevel = "info"

[server]
headless = true
port = 8501
address = "0.0.0.0"
maxUploadSize = 1000
maxMessageSize = 500
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
showErrorDetails = false

[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[client]
caching = true
displayEnabled = true

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true
fastReruns = true
