# Streamlit secrets配置文件
# 在生產環境中使用

# 系統密碼（請更改為強密碼）
password = "your-secure-password-here"

# 資料庫配置（如果需要）
[database]
host = "localhost"
port = 5432
username = "elta_user"
password = "db_password"
name = "elta_analysis"

# API密鑰（如果有外部API）
[api_keys]
tmdb_key = "your-tmdb-api-key"
omdb_key = "your-omdb-api-key"

# 郵件配置（用於錯誤通知）
[email]
smtp_server = "smtp.gmail.com"
smtp_port = 587
username = "your-email@gmail.com"
password = "your-app-password"
